# Generated by Django 4.2 on 2023-04-19 17:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mark",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="name")),
            ],
            options={
                "verbose_name": "Метка",
                "verbose_name_plural": "Метки",
                "db_table": 'content"."mark',
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="filmwork",
            name="age_limit",
            field=models.IntegerField(
                choices=[(0, "Zero"), (6, "Six"), (12, "Twelve"), (16, "Sixteen"), (18, "Eighteen")], default=0
            ),
        ),
        migrations.CreateModel(
            name="MarkFilmwork",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("film_work", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="movies.filmwork")),
                ("mark", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="movies.mark")),
            ],
            options={
                "verbose_name": "Метка фильма",
                "verbose_name_plural": "Метки фильма",
                "db_table": 'content"."mark_film_work',
            },
        ),
        migrations.AddField(
            model_name="filmwork",
            name="marks",
            field=models.ManyToManyField(through="movies.MarkFilmwork", to="movies.mark"),
        ),
        migrations.AddConstraint(
            model_name="markfilmwork",
            constraint=models.UniqueConstraint(fields=("film_work", "mark"), name="unique_film_work_mark"),
        ),
    ]
